services:
  # 1. Il Simulatore IoT fornito dal professore
  mars-simulator:
    image: mars-iot-simulator:multiarch_v1 # Assicurati di aver fatto il load dell'immagine
    ports:
      - "8080:8080"
    networks:
      - mars-network

  # 2. Message Broker (RabbitMQ - compatibile con pika/AMQP 0-9-1)
  message-broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web management UI
    networks:
      - mars-network

  # 3. Database per la persistenza delle regole (Esempio: PostgreSQL)
  rule-database:
    build: 
      context: ./database # Cerca il Dockerfile in questa cartella
    environment:
      POSTGRES_USER: mars_user
      POSTGRES_PASSWORD: mars_password
      POSTGRES_DB: rules_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mars-network

  # 4. Servizio di Ingestione (da costruire)
  ingestion-service:
    build: 
      context: ./ingestion_service # Cerca il Dockerfile in questa cartella
    depends_on:
      - mars-simulator
      - message-broker
    networks:
      - mars-network

  # 5. Motore di Automazione (da costruire)
  automation-engine:
    build: 
      context: ./automation_engine # Cerca il Dockerfile in questa cartella
    ports:
      - "6000:6000"
    depends_on:
      - message-broker
      - rule-database
    networks:
      - mars-network

  #6. Modulo Presentazione
  presentation-service:
    build:
      context: ./presentation_service
    ports:
      - "5050:5050"
    depends_on:
      - message-broker
      - ingestion-service
    networks:
      - mars-network

  state:
    build:
      context: ./state
    ports:
      - "6001:6001"
    #depends_on:
    #  - message-broker
    #  - ingestion-service
    #  - mars-simulator
    networks:
      - mars-network

volumes:
  postgres_data:

networks:
  mars-network:
    driver: bridge
